# Generated by Django 3.2 on 2022-01-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20210905_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='order_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
