# Generated by Django 3.2.4 on 2022-01-24 13:08

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_account_order_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoraccount',
            name='companypan',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vendoraccount',
            name='companypan_image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.get_uplaod_file_name),
        ),
    ]
