# Generated by Django 3.2 on 2022-01-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_vendoraccount_order_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendoraccount',
            name='pickup_address',
        ),
        migrations.AddField(
            model_name='vendoraccount',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
