# Generated by Django 3.2.4 on 2022-02-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20220124_1838'),
        ('account', '0015_auto_20220119_2257'),
    ]

    operations = [
    ]
