# Generated by Django 3.2.8 on 2022-02-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='order_history',
        ),
        migrations.RemoveField(
            model_name='account',
            name='viewpass',
        ),
    ]
