# Generated by Django 3.2.8 on 2022-03-04 03:27

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20220219_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendoraccount',
            name='aadhaar_card',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='aadhaar_image',
            field=models.ImageField(blank=True, upload_to=account.models.get_uplaod_file_name),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='bank_ifsc_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='companypan',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='companypan_image',
            field=models.ImageField(blank=True, upload_to=account.models.get_uplaod_file_name),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='gst',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='logo',
            field=models.ImageField(blank=True, upload_to=account.models.get_uplaod_file_name),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='order_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='pan',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='pan_image',
            field=models.ImageField(blank=True, upload_to=account.models.get_uplaod_file_name),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='pincode',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='shop_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='vat',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
