# Generated by Django 3.2.8 on 2022-03-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20220304_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendoraccount',
            name='shop_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
