# Generated by Django 3.2.8 on 2022-04-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_vendoraccount_shop_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendoraccount',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
