# Generated by Django 3.2.8 on 2022-04-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
