# Generated by Django 3.1.7 on 2021-05-16 20:12

import blog.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.models.get_uplaod_file_name)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.bloggeraccount')),
            ],
        ),
    ]
