# Generated by Django 3.2.8 on 2022-03-13 14:02

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0024_alter_vendoraccount_shop_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('subcategory1', models.CharField(blank=True, max_length=100)),
                ('subcategory2', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('product_for', models.CharField(choices=[('men', 'MEN'), ('women', 'WOMEN'), ('boy', 'BOY'), ('girl', 'GIRL'), ('general', 'GENERAL')], default='general', max_length=7)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('tags', models.CharField(blank=True, default='blanktag', max_length=500, null=True)),
                ('material', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('in_stock', models.BooleanField(default=False)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('mrp', models.FloatField(blank=True, default=60.0, null=True)),
                ('special_price', models.FloatField(blank=True, null=True)),
                ('our_price', models.FloatField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('short_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('weight', models.FloatField(default=0.0, null=True)),
                ('length', models.FloatField(default=0.0, null=True)),
                ('width', models.FloatField(default=0.0, null=True)),
                ('height', models.FloatField(default=0.0, null=True)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('is_recycled', models.BooleanField(default=False)),
                ('is_upcycled', models.BooleanField(default=False)),
                ('is_ecofriendly', models.BooleanField(default=False)),
                ('has_variation', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to=shop.models.get_uplaod_file_name)),
                ('image2', models.ImageField(blank=True, max_length=500, null=True, upload_to=shop.models.get_uplaod_file_name)),
                ('image3', models.ImageField(blank=True, max_length=500, null=True, upload_to=shop.models.get_uplaod_file_name)),
                ('image4', models.ImageField(blank=True, max_length=500, null=True, upload_to=shop.models.get_uplaod_file_name)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.vendoraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('in_stock', models.BooleanField(default=False)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('mrp', models.FloatField(blank=True, default=60.0, null=True)),
                ('special_price', models.FloatField(blank=True, null=True)),
                ('our_price', models.FloatField(blank=True, null=True)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.models.get_uplaod_file_name_variation)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=shop.models.get_uplaod_file_name_variation)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=shop.models.get_uplaod_file_name_variation)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('address2', models.CharField(blank=True, max_length=150, null=True)),
                ('zipcode', models.IntegerField(default=0)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('contact_number', models.IntegerField()),
                ('total', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('waiting', 'NOTPLACED'), ('placed', 'PLACED'), ('accepted', 'ACCEPTED'), ('packed', 'PACKED'), ('shipped', 'SHIPPED'), ('delivered', 'DELIVERED')], default='waiting', max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('order_list', models.JSONField(blank=True, default=list, null=True)),
                ('transaction_id', models.CharField(default='', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='My_Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartdata', models.JSONField(blank=True, default=list, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
