# Generated by Django 3.2.8 on 2022-03-14 06:23

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='gst',
            field=models.CharField(choices=[('5', '5'), ('12', '12'), ('18', '18'), ('28', '28')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
