# Generated by Django 3.1.7 on 2021-06-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory1',
            old_name='subcategory1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory2',
            old_name='subcategory2',
            new_name='name',
        ),
    ]
