# Generated by Django 3.2.4 on 2021-06-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210625_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='property',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
