# Generated by Django 3.2 on 2021-07-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cod_available',
            new_name='in_stock',
        ),
    ]
