# Generated by Django 3.2.8 on 2022-03-15 11:51

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20220315_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='image',
        ),
        migrations.AddField(
            model_name='variation',
            name='image1',
            field=models.ImageField(default='', upload_to=shop.models.get_uplaod_file_name_variation),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variation',
            name='image4',
            field=models.ImageField(default='', upload_to=shop.models.get_uplaod_file_name_variation),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variation',
            name='image2',
            field=models.ImageField(default='', upload_to=shop.models.get_uplaod_file_name_variation),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variation',
            name='image3',
            field=models.ImageField(default='', upload_to=shop.models.get_uplaod_file_name_variation),
            preserve_default=False,
        ),
    ]
