# Generated by Django 3.2 on 2021-07-12 15:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_cod_available_product_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_charge',
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(default=50.0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_ecofriendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_recycle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_upcycle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(default=50.0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='default', max_length=60, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=5.0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(default=50.0, null=True),
        ),
    ]
