# Generated by Django 3.2.8 on 2022-03-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20220315_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='image4',
        ),
        migrations.AddField(
            model_name='variation',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
