# Generated by Django 3.2 on 2021-07-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210712_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='mrp',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='original_price',
            new_name='special_price',
        ),
    ]
