# Generated by Django 3.2.8 on 2022-04-03 09:40

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='image1',
            field=models.ImageField(max_length=500, upload_to=shop.models.get_uplaod_file_name_variation),
        ),
        migrations.AlterField(
            model_name='variation',
            name='image2',
            field=models.ImageField(max_length=500, upload_to=shop.models.get_uplaod_file_name_variation),
        ),
        migrations.AlterField(
            model_name='variation',
            name='image3',
            field=models.ImageField(max_length=500, upload_to=shop.models.get_uplaod_file_name_variation),
        ),
    ]
