# Generated by Django 3.2 on 2021-07-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210715_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='username',
            new_name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='our_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='special_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
