# Generated by Django 3.2 on 2021-07-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='previous_order',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
