# Generated by Django 3.2 on 2021-07-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210716_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, default='blanktag', max_length=500, null=True),
        ),
    ]
