# Generated by Django 3.2 on 2021-07-27 13:53

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_variationp',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('in_stock', models.BooleanField(default=False)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('mrp', models.FloatField(blank=True, default=60.0, null=True)),
                ('special_price', models.FloatField(blank=True, null=True)),
                ('our_price', models.FloatField(blank=True, null=True)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(default='', upload_to=shop.models.get_uplaod_file_name)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=shop.models.get_uplaod_file_name)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=shop.models.get_uplaod_file_name)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
