# Generated by Django 3.2 on 2021-07-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210727_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_variationp',
            new_name='has_variation',
        ),
    ]
