# Generated by Django 3.2 on 2021-07-27 14:22

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_rename_has_variationp_product_has_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='image',
            field=models.ImageField(default='', upload_to=shop.models.get_uplaod_file_name_variation),
        ),
        migrations.AlterField(
            model_name='variation',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.get_uplaod_file_name_variation),
        ),
        migrations.AlterField(
            model_name='variation',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.get_uplaod_file_name_variation),
        ),
    ]
