# Generated by Django 3.2 on 2021-08-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20210825_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_recycle',
            new_name='is_recycled',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_upcycle',
            new_name='is_upcycled',
        ),
    ]
