# Generated by Django 3.2 on 2021-08-27 17:11

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20210825_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.get_uplaod_file_name),
        ),
        migrations.AlterField(
            model_name='variation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.get_uplaod_file_name_variation),
        ),
    ]
