# Generated by Django 3.2 on 2021-09-04 12:09

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.get_uplaod_category),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.get_uplaod_category),
        ),
    ]
