# Generated by Django 3.2.8 on 2022-03-06 04:40

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20220226_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=shop.models.get_uplaod_file_name),
        ),
    ]
