# Generated by Django 3.2.8 on 2022-03-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20220306_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default='2019-09-12'),
            preserve_default=False,
        ),
    ]
